# Generated by Django 4.1.2 on 2022-11-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicemodel",
            name="cost",
            field=models.FloatField(default=0.0),
        ),
    ]
