# Generated by Django 4.1.2 on 2022-11-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="razorpay_currency",
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="razorpay_payment_id",
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
