# Generated by Django 4.1.2 on 2022-11-03 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddressModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("building_name", models.CharField(max_length=64)),
                ("street", models.CharField(max_length=64)),
                ("place", models.CharField(max_length=64)),
                ("city", models.CharField(max_length=64)),
                ("district", models.CharField(max_length=64)),
                ("country", models.CharField(max_length=64)),
                ("post_office", models.CharField(max_length=64)),
                ("post_code", models.CharField(max_length=8)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LocationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lattitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="ProfileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=24)),
                ("last_name", models.CharField(max_length=24)),
                (
                    "gender",
                    models.CharField(
                        choices=[("m", "Male"), ("f", "Female"), ("t", "Transgender")],
                        max_length=15,
                    ),
                ),
                ("phone", models.CharField(max_length=15)),
                (
                    "image",
                    models.ImageField(
                        default="default/user.png", upload_to="user/profile/image/"
                    ),
                ),
                ("address", models.ManyToManyField(to="user.addressmodel")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="addressmodel",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.locationmodel",
            ),
        ),
    ]
