# Generated by Django 4.1.2 on 2022-11-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_profilemodel_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilemodel",
            name="phone",
            field=models.IntegerField(),
        ),
    ]
