# Generated by Django 4.1.2 on 2022-11-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_alter_profilemodel_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilemodel",
            name="phone",
            field=models.CharField(default=None, max_length=15),
        ),
    ]
